# Generated by Django 5.2.7 on 2025-12-30 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='事件名称', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('weather', '天气事件'), ('magic', '魔法事件'), ('system', '系统事件'), ('special', '特殊事件')], max_length=20)),
                ('title', models.CharField(help_text='事件标题', max_length=200)),
                ('description', models.TextField(help_text='事件描述内容')),
                ('schedule_type', models.CharField(choices=[('manual', '手动触发'), ('interval_hours', '小时间隔'), ('interval_days', '天数间隔'), ('cron', '定时触发')], max_length=20)),
                ('interval_value', models.IntegerField(blank=True, help_text='间隔数值', null=True)),
                ('cron_expression', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '事件定义',
                'verbose_name_plural': '事件定义',
                'db_table': 'event_definitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventEffect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effect_type', models.CharField(choices=[('coins_add', '增加积分'), ('coins_subtract', '减少积分'), ('item_distribute', '分发道具'), ('item_remove', '移除道具'), ('store_discount', '商店折扣'), ('store_price_increase', '商店涨价'), ('task_freeze_all', '冻结所有任务'), ('task_unfreeze_all', '解冻所有任务'), ('task_time_add', '任务加时'), ('task_time_subtract', '任务减时'), ('overtime_effect_double', '加时效果翻倍'), ('game_multiplier', '游戏效果倍增'), ('game_reverse_outcome', '游戏结果反转'), ('key_holder_operation', '钥匙持有者操作'), ('temporary_coins_multiplier', '临时积分倍数'), ('temporary_game_enhancement', '临时游戏增强')], max_length=30)),
                ('target_type', models.CharField(choices=[('all_users', '全体用户'), ('random_percentage', '随机百分比'), ('level_based', '等级筛选'), ('active_task_users', '有活跃任务的用户'), ('recent_active_users', '最近活跃用户')], max_length=20)),
                ('effect_parameters', models.JSONField(default=dict, help_text='效果参数配置')),
                ('target_parameters', models.JSONField(default=dict, help_text='目标用户筛选参数')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='效果持续时间', null=True)),
                ('priority', models.IntegerField(default=0, help_text='执行优先级')),
                ('is_active', models.BooleanField(default=True)),
                ('event_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='events.eventdefinition')),
            ],
            options={
                'verbose_name': '事件效果',
                'verbose_name_plural': '事件效果',
                'db_table': 'event_effects',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('executing', '执行中'), ('completed', '已完成'), ('failed', '执行失败'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(help_text='计划执行时间')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('affected_users_count', models.IntegerField(default=0)),
                ('execution_log', models.JSONField(default=list, help_text='执行日志')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('trigger_type', models.CharField(default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.eventdefinition')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '事件发生记录',
                'verbose_name_plural': '事件发生记录',
                'db_table': 'event_occurrences',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='EventEffectExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('effect_data', models.JSONField(default=dict, help_text='具体执行的效果数据')),
                ('rollback_data', models.JSONField(default=dict, help_text='回滚所需数据')),
                ('is_rolled_back', models.BooleanField(default=False)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventeffect')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_event_effects', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_executions', to='events.eventoccurrence')),
            ],
            options={
                'verbose_name': '事件效果执行记录',
                'verbose_name_plural': '事件效果执行记录',
                'db_table': 'event_effect_executions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoinsMultiplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('multiplier', models.FloatField(default=1.0, help_text='积分倍数')),
                ('expires_at', models.DateTimeField(help_text='过期时间')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventeffectexecution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins_multipliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户积分倍数',
                'verbose_name_plural': '用户积分倍数',
                'db_table': 'user_coins_multipliers',
            },
        ),
        migrations.CreateModel(
            name='UserGameEffect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effect_type', models.CharField(default='multiplier', help_text='效果类型', max_length=30)),
                ('multiplier', models.FloatField(default=1.0, help_text='倍数效果')),
                ('expires_at', models.DateTimeField(help_text='过期时间')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventeffectexecution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_effects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户游戏效果',
                'verbose_name_plural': '用户游戏效果',
                'db_table': 'user_game_effects',
            },
        ),
        migrations.AddIndex(
            model_name='eventeffectexecution',
            index=models.Index(fields=['target_user', '-executed_at'], name='event_effec_target__23fbd3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventeffectexecution',
            index=models.Index(fields=['expires_at'], name='event_effec_expires_ac371c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventeffectexecution',
            index=models.Index(fields=['occurrence', 'effect'], name='event_effec_occurre_bfa479_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoinsmultiplier',
            index=models.Index(fields=['user', 'is_active', 'expires_at'], name='user_coins__user_id_20f9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoinsmultiplier',
            index=models.Index(fields=['expires_at'], name='user_coins__expires_3f1513_idx'),
        ),
        migrations.AddIndex(
            model_name='usergameeffect',
            index=models.Index(fields=['user', 'is_active', 'expires_at'], name='user_game_e_user_id_1ad649_idx'),
        ),
        migrations.AddIndex(
            model_name='usergameeffect',
            index=models.Index(fields=['expires_at'], name='user_game_e_expires_d44813_idx'),
        ),
    ]
