"""
Django settings for lockup_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-%-8f8s31opa=&9n$m2ynjv9ci$r#@fgl7pn43lzm@kokayhu7y')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'lock-up.zheermao.top,lock-down.zheermao.top,localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'anymail',
    # Celery apps
    'django_celery_beat',
    'django_celery_results',
    # Custom apps
    'users',
    'posts',
    'tasks',
    'store',
    'telegram_bot',
    'events',
    'utils',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lockup_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lockup_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Production: Use PostgreSQL from DATABASE_URL
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # Development: Use SQLite with optimizations for Celery tasks
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # SQLite optimizations for concurrent access
            'OPTIONS': {
                'init_command': (
                    "PRAGMA journal_mode=WAL; "
                    "PRAGMA synchronous=NORMAL; "
                    "PRAGMA temp_store=MEMORY; "
                    "PRAGMA mmap_size=268435456; "  # 256MB
                    "PRAGMA cache_size=2000; "
                    "PRAGMA busy_timeout=30000;"  # 30 seconds
                ),
                'timeout': 30,  # 30 seconds timeout for database operations
            },
        }
    }

# Database connection settings for SQLite optimization
if not DATABASE_URL:  # Only apply to SQLite
    # Close database connections after each request to avoid locking issues
    DATABASES['default']['CONN_MAX_AGE'] = 0

    # Additional database settings for better SQLite performance
    DATABASE_OPTIONS = {
        'timeout': 30,  # 30 second timeout for database operations
        'check_same_thread': False,  # Allow SQLite to be accessed from multiple threads
    }
    DATABASES['default']['OPTIONS'].update(DATABASE_OPTIONS)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS_ENV = os.getenv('CORS_ALLOWED_ORIGINS', '')
if CORS_ALLOWED_ORIGINS_ENV:
    # Production: Use environment variable
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_ENV.split(',')]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    # Development/Default: Use predefined origins
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",  # React dev server
        "http://127.0.0.1:3000",
        "http://localhost:5173",  # Vite dev server
        "http://127.0.0.1:5173",
        "http://localhost:8000",  # Django admin
        "http://127.0.0.1:8000",
        "https://lock-down.zheermao.top",
        "https://lock-up.zheermao.top",
    ]
    # 开发环境允许所有来源（仅用于开发）
    if DEBUG:
        CORS_ALLOW_ALL_ORIGINS = True
        CORS_ALLOWED_ORIGINS = []

CORS_ALLOW_CREDENTIALS = True

# 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# 允许的HTTP方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Custom user model
AUTH_USER_MODEL = 'users.User'

# JWT Settings
import datetime
JWT_AUTH = {
    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_ALGORITHM': 'HS256',
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_ALLOW_REFRESH': True,
}

# Telegram Bot Configuration - 强制生产环境配置
TELEGRAM_BOT_TOKEN = '8476746874:AAGig__0E_s-BG34kgD9L4ElFy1Z1ymRoBM'  # 生产环境强制设置
TELEGRAM_BOT_USERNAME = 'lock_heart_bot'  # 生产环境强制设置
TELEGRAM_WEBHOOK_URL = 'https://lock-down.zheermao.top/api/telegram/webhook/'  # 生产环境强制设置

# Telegram Security Configuration (生产环境必须配置)
TELEGRAM_SECURITY = {
    'WEBHOOK_SECRET_TOKEN': os.getenv('TELEGRAM_WEBHOOK_SECRET', None),  # 生产环境必须设置
    'RATE_LIMITING_ENABLED': os.getenv('TELEGRAM_RATE_LIMIT_ENABLED', 'True').lower() == 'true',
    'MAX_REQUESTS_PER_MINUTE': int(os.getenv('TELEGRAM_MAX_REQUESTS_PER_MINUTE', '60')),
    # IP 白名单 - Telegram 官方 IP 范围
    'IP_WHITELIST': os.getenv('TELEGRAM_IP_WHITELIST', '').split(',') if os.getenv('TELEGRAM_IP_WHITELIST') else [],
    # 允许的更新类型
    'ALLOWED_UPDATES': ['message', 'callback_query'],
}

# Telegram Bot Application Configuration
TELEGRAM_BOT_CONFIG = {
    'AUTO_START_BOT': os.getenv('TELEGRAM_AUTO_START_BOT', 'True').lower() == 'true',
}

# Application URLs Configuration
TELEGRAM_APP_CONFIG = {
    'BASE_URL': os.getenv('BASE_URL', 'https://lock-down.zheermao.top'),
    'FRONTEND_URL': os.getenv('FRONTEND_URL', 'https://lock-up.zheermao.top'),
}

# Frontend URL for sharing links and external references
# Automatically choose URL based on environment:
# - Local development (DEBUG=True): localhost:5173
# - Production (DEBUG=False): production domain
if DEBUG:
    # Development environment - use localhost with frontend dev server port
    FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')
else:
    # Production environment - automatically use production domain
    FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://lock-up.zheermao.top')

# Production Security Settings (only if not in DEBUG mode)
if not DEBUG:
    # SSL/HTTPS Settings
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() == 'true'
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'True').lower() == 'true'

    # Cookie Security
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True').lower() == 'true'
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True').lower() == 'true'

    # Additional Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# =============================================================================
# CELERY CONFIGURATION
# =============================================================================

# Celery Broker settings (Redis)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Celery Task settings
CELERY_TASK_ALWAYS_EAGER = os.getenv('CELERY_ALWAYS_EAGER', 'False').lower() == 'true'
CELERY_TASK_EAGER_PROPAGATES = True

# Celery Security settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Celery Timezone settings
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Celery Worker settings - SQLite optimized
# Use single process for SQLite to avoid database locking issues
CELERY_WORKER_CONCURRENCY = int(os.getenv('CELERY_WORKER_CONCURRENCY', '1'))
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 500  # Reduced for SQLite stability

# Celery Task execution settings - SQLite optimized
CELERY_TASK_SOFT_TIME_LIMIT = 600   # 10 minutes (increased for SQLite)
CELERY_TASK_TIME_LIMIT = 1200       # 20 minutes (increased for SQLite)
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# SQLite-specific task retry settings
CELERY_TASK_RETRY_DELAY = 60        # 1 minute base retry delay
CELERY_TASK_MAX_RETRIES = 3         # Maximum retry attempts

# Celery Result settings
CELERY_RESULT_EXPIRES = 3600  # 1 hour

# Celery Logging settings
CELERY_WORKER_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
CELERY_WORKER_TASK_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s][%(task_name)s(%(task_id)s)] %(message)s'

# Celery Beat settings (for periodic tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery Monitoring settings
CELERY_SEND_TASK_EVENTS = True
CELERY_WORKER_SEND_TASK_EVENTS = True

# =============================================================================
# CELERY LOGGING CONFIGURATION
# =============================================================================

# Update LOGGING configuration to include Celery
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'celery': {
            'format': '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024*1024*15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'celery.log',
            'maxBytes': 1024*1024*15,  # 15MB
            'backupCount': 10,
            'formatter': 'celery',
        },
    },
    'root': {
        'level': 'INFO',
        'handlers': ['console'] if DEBUG else ['console', 'file'],
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'celery_file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.task': {
            'handlers': ['console', 'celery_file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'tasks.celery_tasks': {
            'handlers': ['console', 'celery_file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================

# Main SMTP relay: Mailgun
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
ANYMAIL = {
   "MAILGUN_API_KEY": os.getenv('MAILGUN_API_KEY', ''),
   "MAILGUN_SENDER_DOMAIN": os.getenv('MAILGUN_SENDER_DOMAIN', 'lock-up.zheermao.top'),
}

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', "noreply@lock-up.zheermao.top")
SERVER_EMAIL = os.getenv('SERVER_EMAIL', "server@lock-up.zheermao.top")


# fallback SMTP relay: Local SMTP server postfix or external SMTP
FALLBACK_EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
FALLBACK_EMAIL_HOST = os.getenv('FALLBACK_EMAIL_HOST', 'localhost')
FALLBACK_EMAIL_PORT = int(os.getenv('FALLBACK_EMAIL_PORT', '25'))
FALLBACK_EMAIL_USE_TLS = os.getenv('FALLBACK_EMAIL_USE_TLS', 'False').lower() == 'true'
FALLBACK_EMAIL_HOST_USER = os.getenv('FALLBACK_EMAIL_HOST_USER', '')
FALLBACK_EMAIL_HOST_PASSWORD = os.getenv('FALLBACK_EMAIL_HOST_PASSWORD', '')