# Generated by Django 5.2.7 on 2025-10-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driftbottle',
            old_name='attached_items',
            new_name='items',
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', '可用'), ('used', '已使用'), ('expired', '已过期'), ('in_drift_bottle', '在漂流瓶中'), ('buried', '已掩埋')], default='available', max_length=20),
        ),
    ]
