# Generated by Django 5.2.7 on 2025-12-08 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_attached_items_driftbottle_items_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='original_owner',
            field=models.ForeignKey(blank=True, help_text='原始拥有者（如任务创建者）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='originally_owned_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
