# Generated by Django 5.2.7 on 2025-12-08 07:02

from django.db import migrations
from django.contrib.auth import get_user_model


def populate_key_owners(apps, schema_editor):
    """
    Populate the original_owner field for existing key items.
    Set all historical keys to be owned by 'burier' user.
    """
    User = get_user_model()
    Item = apps.get_model('store', 'Item')
    ItemType = apps.get_model('store', 'ItemType')

    # Get or create the 'burier' user
    burier, created = User.objects.get_or_create(
        username='burier',
        defaults={
            'email': 'burier@example.com',
            'is_active': True,
        }
    )

    if created:
        print(f"Created burier user with ID: {burier.id}")
    else:
        print(f"Using existing burier user with ID: {burier.id}")

    # Get the key item type
    try:
        key_type = ItemType.objects.get(name='key')

        # Update all key items that don't have an original_owner
        key_items = Item.objects.filter(item_type=key_type, original_owner__isnull=True)
        updated_count = key_items.update(original_owner=burier)

        print(f"Updated {updated_count} key items to have burier as original_owner")

    except ItemType.DoesNotExist:
        print("Key item type not found, skipping key owner population")


def reverse_populate_key_owners(apps, schema_editor):
    """
    Reverse migration: set original_owner back to null for all key items.
    """
    Item = apps.get_model('store', 'Item')
    ItemType = apps.get_model('store', 'ItemType')

    try:
        key_type = ItemType.objects.get(name='key')
        key_items = Item.objects.filter(item_type=key_type)
        updated_count = key_items.update(original_owner=None)
        print(f"Reset {updated_count} key items' original_owner to null")

    except ItemType.DoesNotExist:
        print("Key item type not found, skipping reverse migration")


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_original_owner_to_item'),
    ]

    operations = [
        migrations.RunPython(
            populate_key_owners,
            reverse_populate_key_owners,
        ),
    ]
