# Generated by Django 5.2.7 on 2025-12-13 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_populate_historical_key_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', '可用'), ('used', '已使用'), ('expired', '已过期'), ('in_drift_bottle', '在漂流瓶中'), ('buried', '已掩埋'), ('shared', '已分享')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='SharedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(help_text='分享链接的唯一标识符', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', '可领取'), ('claimed', '已领取'), ('expired', '已过期')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='分享链接过期时间')),
                ('claimer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_shared_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
