# Generated by Django 5.2.7 on 2025-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_itemtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(choices=[('photo_paper', '相纸'), ('photo', '照片'), ('drift_bottle', '漂流瓶'), ('key', '钥匙'), ('note', '纸条'), ('little_treasury', '小金库'), ('detection_radar', '探测雷达'), ('blizzard_bottle', '暴雪瓶')], max_length=50, unique=True),
        ),
    ]
