# Generated by Django 5.2.7 on 2025-12-27 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_itemtype_name'),
        ('tasks', '0020_add_hourglass_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('time_wheel', '时间转盘'), ('rock_paper_scissors', '石头剪刀布'), ('exploration', '探索'), ('dice', '掷骰子')], max_length=30),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(choices=[('photo_paper', '相纸'), ('photo', '照片'), ('drift_bottle', '漂流瓶'), ('key', '钥匙'), ('note', '纸条'), ('little_treasury', '小金库'), ('detection_radar', '探测雷达'), ('blizzard_bottle', '暴雪瓶'), ('sun_bottle', '太阳瓶'), ('time_hourglass', '时间沙漏')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='UserHourglassPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('task_used_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.locktask')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hourglass_purchase', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_user_hourglass_purchase',
            },
        ),
    ]
