# Generated by Django 5.2.7 on 2026-01-02 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_add_hourglass_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(choices=[('photo_paper', '相纸'), ('photo', '照片'), ('drift_bottle', '漂流瓶'), ('key', '钥匙'), ('note', '纸条'), ('little_treasury', '小金库'), ('detection_radar', '探测雷达'), ('blizzard_bottle', '暴雪瓶'), ('sun_bottle', '太阳瓶'), ('time_hourglass', '时间沙漏'), ('lucky_charm', '幸运符'), ('energy_potion', '活力药水'), ('friendship_bridge', '友谊桥梁'), ('time_anchor', '时间锚点'), ('exploration_compass', '探索指南针'), ('spacetime_gate', '时空之门'), ('influence_crown', '影响力皇冠')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='TaskSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.UUIDField()),
                ('snapshot_data', models.JSONField()),
                ('can_restore', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_snapshots', to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedTaskAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.UUIDField()),
                ('can_view_progress', models.BooleanField(default=True)),
                ('can_view_timeline', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_shares', to='store.item')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_tasks', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewable_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sharer', 'viewer', 'task_id')},
            },
        ),
        migrations.CreateModel(
            name='UserEffect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effect_type', models.CharField(choices=[('lucky_charm', '幸运符效果'), ('energy_potion', '活力药水效果'), ('friendship_bridge', '友谊桥梁效果'), ('time_anchor', '时间锚点效果'), ('exploration_compass', '探索指南针效果'), ('spacetime_gate', '时空之门效果'), ('influence_crown', '影响力皇冠效果')], max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_effects', to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_effects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'effect_type', 'is_active'], name='store_usere_user_id_d1bc95_idx'), models.Index(fields=['expires_at'], name='store_usere_expires_e1de7b_idx')],
            },
        ),
    ]
