# Generated by Django 5.2.7 on 2026-01-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_itemtype_name_tasksnapshot_sharedtaskaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(choices=[('photo_paper', '相纸'), ('photo', '照片'), ('drift_bottle', '漂流瓶'), ('key', '钥匙'), ('note', '纸条'), ('little_treasury', '小金库'), ('detection_radar', '探测雷达'), ('blizzard_bottle', '暴雪瓶'), ('sun_bottle', '太阳瓶'), ('time_hourglass', '时间沙漏'), ('lucky_charm', '幸运符'), ('energy_potion', '活力药水'), ('time_anchor', '时间锚点'), ('exploration_compass', '探索指南针'), ('influence_crown', '影响力皇冠'), ('small_campfire', '小火堆')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usereffect',
            name='effect_type',
            field=models.CharField(choices=[('lucky_charm', '幸运符效果'), ('energy_potion', '活力药水效果'), ('time_anchor', '时间锚点效果'), ('exploration_compass', '探索指南针效果'), ('influence_crown', '影响力皇冠效果')], max_length=50),
        ),
    ]
