# Generated by Django 5.2.11 on 2026-02-21 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_itemtype_name_alter_usereffect_effect_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserZoneExploration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=50)),
                ('exploration_date', models.DateField()),
                ('daily_count', models.IntegerField(default=0)),
                ('last_exploration_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_explorations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'zone_name', 'exploration_date'], name='store_userz_user_id_9ec020_idx')],
                'unique_together': {('user', 'zone_name', 'exploration_date')},
            },
        ),
    ]
