# Generated by Django 5.2.11 on 2026-02-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_userzoneexploration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', '可用'), ('used', '已使用'), ('expired', '已过期'), ('in_drift_bottle', '在漂流瓶中'), ('buried', '已掩埋'), ('shared', '已分享'), ('in_game', '游戏中')], default='available', max_length=20),
        ),
    ]
