# Generated by Django 5.2.11 on 2026-02-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('time_wheel', '时间转盘'), ('rock_paper_scissors', '石头剪刀布'), ('exploration', '探索'), ('dice', '掷骰子'), ('arena', '角斗场')], max_length=30),
        ),
    ]
