# Generated by Django 5.2.7 on 2025-10-11 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LockTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('lock', '带锁任务'), ('board', '任务板')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待开始'), ('active', '进行中'), ('completed', '已完成'), ('failed', '已失败'), ('open', '开放中'), ('taken', '已接取')], default='pending', max_length=20)),
                ('duration_type', models.CharField(blank=True, choices=[('fixed', '固定时间'), ('random', '随机时间')], max_length=10, null=True)),
                ('duration_value', models.IntegerField(blank=True, help_text='持续时间（分钟）', null=True)),
                ('duration_max', models.IntegerField(blank=True, help_text='最大持续时间（分钟）- 仅随机类型', null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', '简单'), ('normal', '普通'), ('hard', '困难'), ('hell', '地狱')], max_length=10, null=True)),
                ('unlock_type', models.CharField(blank=True, choices=[('time', '定时解锁'), ('vote', '投票解锁')], max_length=10, null=True)),
                ('vote_threshold', models.IntegerField(blank=True, help_text='投票门槛', null=True)),
                ('vote_agreement_ratio', models.FloatField(blank=True, help_text='同意比例 (0.0-1.0)', null=True)),
                ('overtime_multiplier', models.IntegerField(blank=True, help_text='加时惩罚倍数', null=True)),
                ('overtime_duration', models.IntegerField(blank=True, help_text='置顶时间（分钟）', null=True)),
                ('reward', models.IntegerField(blank=True, help_text='奖励金额', null=True)),
                ('deadline', models.DateTimeField(blank=True, help_text='截止时间', null=True)),
                ('max_duration', models.IntegerField(blank=True, help_text='最大完成时间（小时）', null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('completion_proof', models.TextField(blank=True, help_text='完成证明', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_tasks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', '有效'), ('used', '已使用')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_keys', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key', to='tasks.locktask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agree', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tasks.locktask')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('task', 'voter')},
            },
        ),
    ]
