# Generated by Django 5.2.7 on 2025-10-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locktask',
            name='status',
            field=models.CharField(choices=[('pending', '待开始'), ('active', '进行中'), ('completed', '已完成'), ('failed', '已失败'), ('open', '开放中'), ('taken', '已接取'), ('submitted', '已提交')], default='pending', max_length=20),
        ),
    ]
