# Generated by Django 5.2.7 on 2025-10-12 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_overtimeaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('task_created', '任务创建'), ('task_started', '任务开始'), ('time_wheel_increase', '时间转盘增加时间'), ('time_wheel_decrease', '时间转盘减少时间'), ('overtime_added', '他人加时'), ('task_completed', '任务完成'), ('task_stopped', '任务停止'), ('task_failed', '任务失败'), ('deadline_extended', '截止时间延长'), ('manual_adjustment', '手动调整')], max_length=20)),
                ('time_change_minutes', models.IntegerField(blank=True, help_text='时间变化（分钟）, 正数为增加，负数为减少', null=True)),
                ('previous_end_time', models.DateTimeField(blank=True, help_text='变化前的结束时间', null=True)),
                ('new_end_time', models.DateTimeField(blank=True, help_text='变化后的结束时间', null=True)),
                ('description', models.TextField(blank=True, help_text='事件描述')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='额外的事件数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='tasks.locktask')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='tasks_taskt_task_id_48100e_idx'), models.Index(fields=['event_type', '-created_at'], name='tasks_taskt_event_t_fb8ce4_idx')],
            },
        ),
    ]
