# Generated by Django 5.2.7 on 2025-10-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasktimelineevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktimelineevent',
            name='event_type',
            field=models.CharField(choices=[('task_created', '任务创建'), ('task_started', '任务开始'), ('time_wheel_increase', '时间转盘增加时间'), ('time_wheel_decrease', '时间转盘减少时间'), ('overtime_added', '他人加时'), ('task_voted', '任务投票'), ('task_completed', '任务完成'), ('task_stopped', '任务停止'), ('task_failed', '任务失败'), ('deadline_extended', '截止时间延长'), ('manual_adjustment', '手动调整')], max_length=20),
        ),
    ]
