# Generated by Django 5.2.7 on 2025-10-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasktimelineevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='locktask',
            name='vote_failed_penalty_minutes',
            field=models.IntegerField(blank=True, help_text='投票失败加时分钟数', null=True),
        ),
        migrations.AddField(
            model_name='locktask',
            name='voting_duration',
            field=models.IntegerField(default=10, help_text='投票持续时间（分钟）'),
        ),
        migrations.AddField(
            model_name='locktask',
            name='voting_end_time',
            field=models.DateTimeField(blank=True, help_text='投票结束时间', null=True),
        ),
        migrations.AddField(
            model_name='locktask',
            name='voting_start_time',
            field=models.DateTimeField(blank=True, help_text='投票开始时间', null=True),
        ),
        migrations.AlterField(
            model_name='locktask',
            name='status',
            field=models.CharField(choices=[('pending', '待开始'), ('active', '进行中'), ('voting', '投票期'), ('completed', '已完成'), ('failed', '已失败'), ('open', '开放中'), ('taken', '已接取'), ('submitted', '已提交')], default='pending', max_length=20),
        ),
    ]
