# Generated by Django 5.2.7 on 2025-10-12 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_add_voting_system_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locktask',
            name='last_hourly_reward_at',
            field=models.DateTimeField(blank=True, help_text='上次获得小时奖励的时间', null=True),
        ),
        migrations.AddField(
            model_name='locktask',
            name='total_hourly_rewards',
            field=models.IntegerField(default=0, help_text='总共获得的小时奖励数'),
        ),
        migrations.AlterField(
            model_name='tasktimelineevent',
            name='event_type',
            field=models.CharField(choices=[('task_created', '任务创建'), ('task_started', '任务开始'), ('time_wheel_increase', '时间转盘增加时间'), ('time_wheel_decrease', '时间转盘减少时间'), ('overtime_added', '他人加时'), ('voting_started', '投票期开始'), ('voting_ended', '投票期结束'), ('vote_passed', '投票通过'), ('vote_failed', '投票失败'), ('task_voted', '任务投票'), ('task_completed', '任务完成'), ('task_stopped', '任务停止'), ('task_failed', '任务失败'), ('deadline_extended', '截止时间延长'), ('manual_adjustment', '手动调整')], max_length=20),
        ),
        migrations.CreateModel(
            name='HourlyReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reward_amount', models.IntegerField(default=1, help_text='奖励积分数量')),
                ('hour_count', models.IntegerField(help_text='任务运行的小时数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rewards', to='tasks.locktask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='tasks_hourl_task_id_2b2404_idx'), models.Index(fields=['user', '-created_at'], name='tasks_hourl_user_id_e00776_idx')],
            },
        ),
    ]
