# Generated by Django 5.2.7 on 2025-12-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tasktimelineevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locktask',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
