# Generated by Django 5.2.7 on 2025-12-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_make_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='locktask',
            name='time_display_hidden',
            field=models.BooleanField(default=False, help_text='是否隐藏时间显示'),
        ),
    ]
