# Generated by Django 5.2.7 on 2025-12-16 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_locktask_time_display_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktimelineevent',
            name='event_type',
            field=models.CharField(choices=[('task_created', '任务创建'), ('task_started', '任务开始'), ('time_wheel_increase', '时间转盘增加时间'), ('time_wheel_decrease', '时间转盘减少时间'), ('overtime_added', '他人加时'), ('voting_started', '投票期开始'), ('voting_ended', '投票期结束'), ('vote_passed', '投票通过'), ('vote_failed', '投票失败'), ('task_voted', '任务投票'), ('task_completed', '任务完成'), ('task_stopped', '任务停止'), ('task_failed', '任务失败'), ('deadline_extended', '截止时间延长'), ('manual_adjustment', '手动调整'), ('hourly_reward', '小时奖励'), ('task_keys_destroyed', '任务钥匙销毁')], max_length=20),
        ),
        migrations.CreateModel(
            name='TaskSubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to='task_submissions/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('document', '文档')], default='image', max_length=10)),
                ('file_name', models.CharField(help_text='原始文件名', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='文件大小（字节）')),
                ('description', models.CharField(blank=True, help_text='文件描述', max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='是否为主要证明文件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='tasks.locktask')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_submission_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='tasks_tasks_task_id_ea8141_idx'), models.Index(fields=['uploader', '-created_at'], name='tasks_tasks_uploade_32ed40_idx'), models.Index(fields=['file_type', '-created_at'], name='tasks_tasks_file_ty_54faba_idx')],
            },
        ),
    ]
