# Generated by Django 5.2.7 on 2025-12-17 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_tasktimelineevent_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locktask',
            name='max_participants',
            field=models.IntegerField(default=1, help_text='最大参与人数'),
        ),
        migrations.CreateModel(
            name='TaskParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('joined', '已加入'), ('submitted', '已提交'), ('approved', '已通过'), ('rejected', '已拒绝')], default='joined', max_length=20)),
                ('submission_text', models.TextField(blank=True, help_text='文字提交内容')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, help_text='审核意见')),
                ('reward_amount', models.IntegerField(blank=True, help_text='分配的奖励金额', null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_participations', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tasks.locktask')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddField(
            model_name='tasksubmissionfile',
            name='participant',
            field=models.ForeignKey(blank=True, help_text='关联的参与者（多人任务）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='tasks.taskparticipant'),
        ),
        migrations.AddIndex(
            model_name='taskparticipant',
            index=models.Index(fields=['task', 'status'], name='tasks_taskp_task_id_d000c9_idx'),
        ),
        migrations.AddIndex(
            model_name='taskparticipant',
            index=models.Index(fields=['participant', 'status'], name='tasks_taskp_partici_13cde0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskparticipant',
            unique_together={('task', 'participant')},
        ),
    ]