# Generated by Django 5.2.7 on 2025-12-19 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_locktask_max_participants_taskparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='locktask',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='最大参与人数（仅任务板）', null=True),
        ),
        migrations.AlterField(
            model_name='tasktimelineevent',
            name='event_type',
            field=models.CharField(choices=[('task_created', '任务创建'), ('task_started', '任务开始'), ('time_wheel_increase', '时间转盘增加时间'), ('time_wheel_decrease', '时间转盘减少时间'), ('overtime_added', '他人加时'), ('voting_started', '投票期开始'), ('voting_ended', '投票期结束'), ('vote_passed', '投票通过'), ('vote_failed', '投票失败'), ('task_voted', '任务投票'), ('task_completed', '任务完成'), ('task_stopped', '任务停止'), ('task_failed', '任务失败'), ('deadline_extended', '截止时间延长'), ('manual_adjustment', '手动调整'), ('hourly_reward', '小时奖励'), ('task_keys_destroyed', '任务钥匙销毁'), ('user_pinned', '用户被置顶'), ('user_unpinned', '用户置顶结束'), ('pinning_queue_updated', '置顶队列更新')], max_length=30),
        ),
        migrations.CreateModel(
            name='PinnedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coins_spent', models.IntegerField(default=60, help_text='消费的金币数')),
                ('duration_minutes', models.IntegerField(default=30, help_text='置顶持续时间（分钟）')),
                ('is_active', models.BooleanField(default=True, help_text='是否处于置顶状态')),
                ('position', models.IntegerField(blank=True, help_text='置顶位置（1-3，null表示排队中）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间（排队时间）')),
                ('expires_at', models.DateTimeField(help_text='置顶过期时间')),
                ('activated_at', models.DateTimeField(blank=True, help_text='开始置顶的时间', null=True)),
                ('key_holder', models.ForeignKey(help_text='执行置顶的钥匙持有者', on_delete=django.db.models.deletion.CASCADE, related_name='pinning_actions', to=settings.AUTH_USER_MODEL)),
                ('pinned_user', models.ForeignKey(help_text='被置顶的用户（任务创建者）', on_delete=django.db.models.deletion.CASCADE, related_name='pinned_records', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='被置顶的任务（钥匙对应的任务）', on_delete=django.db.models.deletion.CASCADE, related_name='pinned_records', to='tasks.locktask')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['is_active', 'position'], name='tasks_pinne_is_acti_665d16_idx'), models.Index(fields=['expires_at'], name='tasks_pinne_expires_e0db12_idx'), models.Index(fields=['created_at'], name='tasks_pinne_created_677eb4_idx'), models.Index(fields=['pinned_user', 'is_active'], name='tasks_pinne_pinned__1135d1_idx')],
            },
        ),
    ]
