# Generated by Django 5.2.7 on 2025-12-20 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_locktask_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locktask',
            name='frozen_at',
            field=models.DateTimeField(blank=True, help_text='冻结时间', null=True),
        ),
        migrations.AddField(
            model_name='locktask',
            name='frozen_end_time',
            field=models.DateTimeField(blank=True, help_text='冻结时保存的原始结束时间', null=True),
        ),
        migrations.AddField(
            model_name='locktask',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='是否冻结倒计时'),
        ),
        migrations.AddField(
            model_name='locktask',
            name='total_frozen_duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='总冻结时长'),
        ),
        migrations.AlterField(
            model_name='tasktimelineevent',
            name='event_type',
            field=models.CharField(choices=[('task_created', '任务创建'), ('task_started', '任务开始'), ('time_wheel_increase', '时间转盘增加时间'), ('time_wheel_decrease', '时间转盘减少时间'), ('overtime_added', '他人加时'), ('voting_started', '投票期开始'), ('voting_ended', '投票期结束'), ('vote_passed', '投票通过'), ('vote_failed', '投票失败'), ('task_voted', '任务投票'), ('task_completed', '任务完成'), ('task_stopped', '任务停止'), ('task_failed', '任务失败'), ('deadline_extended', '截止时间延长'), ('manual_adjustment', '手动调整'), ('hourly_reward', '小时奖励'), ('task_keys_destroyed', '任务钥匙销毁'), ('user_pinned', '用户被置顶'), ('user_unpinned', '用户置顶结束'), ('pinning_queue_updated', '置顶队列更新'), ('task_frozen', '任务冻结'), ('task_unfrozen', '任务解冻')], max_length=30),
        ),
    ]
