# Generated by Django 5.2.7 on 2025-12-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_add_freeze_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='locktask',
            name='strict_code',
            field=models.CharField(blank=True, help_text='严格模式随机码', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='locktask',
            name='strict_mode',
            field=models.BooleanField(default=False, help_text='是否为严格模式'),
        ),
    ]
