# Generated by Django 5.2.7 on 2025-12-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_add_strict_mode_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmissionfile',
            name='file',
            field=models.FileField(help_text='任务提交文件（图片、视频、文档）', max_length=500, upload_to='utils.file_upload.secure_task_file_upload_to'),
        ),
    ]
