# Generated by Django 5.2.7 on 2025-12-27 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_tasktimelineevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTimeRollback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rollback_start_time', models.DateTimeField(help_text='回退操作的起始时间（30分钟前）')),
                ('rollback_end_time', models.DateTimeField(help_text='回退操作的结束时间（使用时间沙漏的时间）')),
                ('original_end_time', models.DateTimeField(blank=True, help_text='回退前的任务结束时间', null=True)),
                ('original_is_frozen', models.BooleanField(default=False, help_text='回退前的冻结状态')),
                ('original_frozen_at', models.DateTimeField(blank=True, help_text='回退前的冻结开始时间', null=True)),
                ('original_frozen_end_time', models.DateTimeField(blank=True, help_text='回退前的冻结时保存的结束时间', null=True)),
                ('restored_end_time', models.DateTimeField(blank=True, help_text='回退后的任务结束时间', null=True)),
                ('restored_is_frozen', models.BooleanField(default=False, help_text='回退后的冻结状态')),
                ('restored_frozen_at', models.DateTimeField(blank=True, help_text='回退后的冻结开始时间', null=True)),
                ('restored_frozen_end_time', models.DateTimeField(blank=True, help_text='回退后的冻结时保存的结束时间', null=True)),
                ('reverted_events', models.JSONField(default=list, help_text='被回退的时间线事件列表')),
                ('reverted_events_count', models.IntegerField(default=0, help_text='回退的事件数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollbacks', to='tasks.locktask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '任务时间回退记录',
                'verbose_name_plural': '任务时间回退记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
