# Generated by Django 5.2.7 on 2025-12-30 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_add_hourglass_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDeadlineReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('8h', '8小时前')], help_text='提醒类型', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('participant', models.ForeignKey(help_text='参与者', on_delete=django.db.models.deletion.CASCADE, related_name='deadline_reminders', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='任务', on_delete=django.db.models.deletion.CASCADE, related_name='deadline_reminders', to='tasks.locktask')),
            ],
            options={
                'verbose_name': '任务截止提醒记录',
                'verbose_name_plural': '任务截止提醒记录',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['task', 'reminder_type'], name='tasks_taskd_task_id_e9e9a7_idx'), models.Index(fields=['sent_at'], name='tasks_taskd_sent_at_ddecd4_idx'), models.Index(fields=['participant', 'reminder_type'], name='tasks_taskd_partici_f17e20_idx')],
                'unique_together': {('task', 'participant', 'reminder_type')},
            },
        ),
    ]
