# Generated by Django 5.2.7 on 2025-12-30 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_commentimage_image_alter_postimage_image'),
        ('tasks', '0022_add_verification_code_updated_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='locktask',
            name='auto_created_post',
            field=models.ForeignKey(blank=True, help_text='自动创建的动态', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_task', to='posts.post'),
        ),
        migrations.AddField(
            model_name='locktask',
            name='auto_publish',
            field=models.BooleanField(default=False, help_text='是否自动发布动态'),
        ),
    ]
