# Generated by Claude Code for converting Markdown format links to HTML format
import re
from django.db import migrations


def convert_markdown_links_to_html(apps, schema_editor):
    """
    Convert existing Markdown format links to HTML format in task descriptions.

    This migration finds tasks with Markdown format links like:
    📌 [查看相关动态](http://localhost:5173/posts/xxx)

    And converts them to HTML format:
    📌 <a href="http://localhost:5173/posts/xxx" target="_blank" style="color: #007bff; text-decoration: none;">查看相关动态</a>
    """
    LockTask = apps.get_model('tasks', 'LockTask')

    # Regular expression to match Markdown format links
    # Pattern: 📌 [查看相关动态](url)
    markdown_link_pattern = r'📌\s*\[查看相关动态\]\((http://[^)]+)\)'

    updated_count = 0

    # Find all tasks with Markdown format links
    for task in LockTask.objects.filter(description__contains='📌 [查看相关动态]'):
        original_description = task.description

        # Convert Markdown links to HTML
        def replace_markdown_with_html(match):
            url = match.group(1)
            return f'📌 <a href="{url}" target="_blank" style="color: #007bff; text-decoration: none;">查看相关动态</a>'

        new_description = re.sub(markdown_link_pattern, replace_markdown_with_html, original_description)

        if new_description != original_description:
            task.description = new_description
            task.save(update_fields=['description'])
            updated_count += 1
            print(f"Updated task {task.id}: converted Markdown link to HTML")

    print(f"Migration completed. Updated {updated_count} tasks.")


def reverse_html_links_to_markdown(apps, schema_editor):
    """
    Reverse operation: convert HTML format links back to Markdown format.
    This is for rollback purposes.
    """
    LockTask = apps.get_model('tasks', 'LockTask')

    # Regular expression to match HTML format links
    # Pattern: 📌 <a href="url" target="_blank" style="...">查看相关动态</a>
    html_link_pattern = r'📌\s*<a href="([^"]+)" target="_blank"[^>]*>查看相关动态</a>'

    updated_count = 0

    # Find all tasks with HTML format links
    for task in LockTask.objects.filter(description__contains='<a href='):
        original_description = task.description

        # Convert HTML links to Markdown
        def replace_html_with_markdown(match):
            url = match.group(1)
            return f'📌 [查看相关动态]({url})'

        new_description = re.sub(html_link_pattern, replace_html_with_markdown, original_description)

        if new_description != original_description:
            task.description = new_description
            task.save(update_fields=['description'])
            updated_count += 1
            print(f"Reverted task {task.id}: converted HTML link to Markdown")

    print(f"Rollback completed. Reverted {updated_count} tasks.")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_add_auto_publish_fields'),
    ]

    operations = [
        migrations.RunPython(
            convert_markdown_links_to_html,
            reverse_html_links_to_markdown,
            hints={'description': 'Convert Markdown format auto-post links to HTML format for proper rendering'}
        ),
    ]