# Generated by Django 5.2.7 on 2025-12-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_convert_markdown_links_to_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktimelineevent',
            name='event_type',
            field=models.CharField(choices=[('task_created', '任务创建'), ('task_started', '任务开始'), ('time_wheel_increase', '时间转盘增加时间'), ('time_wheel_decrease', '时间转盘减少时间'), ('overtime_added', '他人加时'), ('voting_started', '投票期开始'), ('voting_ended', '投票期结束'), ('vote_passed', '投票通过'), ('vote_failed', '投票失败'), ('task_voted', '任务投票'), ('task_completed', '任务完成'), ('task_stopped', '任务停止'), ('task_failed', '任务失败'), ('deadline_extended', '截止时间延长'), ('manual_adjustment', '手动调整'), ('hourly_reward', '小时奖励'), ('task_keys_destroyed', '任务钥匙销毁'), ('user_pinned', '用户被置顶'), ('user_unpinned', '用户置顶结束'), ('pinning_queue_updated', '置顶队列更新'), ('task_frozen', '任务冻结'), ('task_unfrozen', '任务解冻'), ('radar_detection', '探测雷达检测'), ('system_freeze', '系统冻结'), ('verification_code_updated', '验证码更新'), ('exclusive_task_created', '专属任务创建')], max_length=30),
        ),
    ]
