# Generated by Django 5.2.7 on 2026-01-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_add_shield_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locktask',
            name='status',
            field=models.CharField(choices=[('pending', '待开始'), ('active', '进行中'), ('voting', '投票期'), ('voting_passed', '投票已通过，等待时间结束'), ('completed', '已完成'), ('failed', '已失败'), ('open', '开放中'), ('taken', '已接取'), ('submitted', '已提交')], default='pending', max_length=20),
        ),
    ]
