# Generated by Django 5.2.7 on 2026-01-02 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_alter_locktask_add_voting_passed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='locktask',
            name='completion_rate_threshold',
            field=models.IntegerField(blank=True, default=0, help_text='任务完成率门槛 (0-100)，仅适用于任务板', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
