# Generated by Django 4.2.7 on 2025-01-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0029_locktask_completion_rate_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskViolationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('premature_completion_hidden_time', '时间隐藏状态下提前完成'), ('multiple_rapid_attempts', '快速多次违规尝试')], help_text='违规类型', max_length=50)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, help_text='尝试时间')),
                ('actual_end_time', models.DateTimeField(help_text='任务实际结束时间')),
                ('attempted_completion_time', models.DateTimeField(help_text='尝试完成时间')),
                ('time_remaining_seconds', models.IntegerField(help_text='剩余时间（秒）')),
                ('penalty_applied', models.BooleanField(default=False, help_text='是否已应用惩罚')),
                ('penalty_minutes', models.IntegerField(blank=True, help_text='惩罚加时分钟数', null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='用户IP地址', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='用户代理字符串', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='额外的违规数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(help_text='相关任务', on_delete=django.db.models.deletion.CASCADE, related_name='violation_attempts', to='tasks.locktask')),
                ('user', models.ForeignKey(help_text='违规用户', on_delete=django.db.models.deletion.CASCADE, related_name='violation_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '任务违规尝试记录',
                'verbose_name_plural': '任务违规尝试记录',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taskviolationattempt',
            index=models.Index(fields=['task', '-attempted_at'], name='tasks_taskv_task_id_e6b34a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskviolationattempt',
            index=models.Index(fields=['user', '-attempted_at'], name='tasks_taskv_user_id_4a7b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskviolationattempt',
            index=models.Index(fields=['violation_type', '-attempted_at'], name='tasks_taskv_violati_9d5e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskviolationattempt',
            index=models.Index(fields=['penalty_applied', '-attempted_at'], name='tasks_taskv_penalty_3c8f7a_idx'),
        ),
    ]