# Generated by Django 5.2.11 on 2026-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_rename_tasks_taskv_task_id_e6b34a_idx_tasks_taskv_task_id_f2efbb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdeadlinereminder',
            name='reminder_type',
            field=models.CharField(choices=[('8h', '8小时前'), ('custom', '自定义时间')], help_text='提醒类型', max_length=10),
        ),
    ]
