# Generated by Django 5.2.11 on 2026-02-23 00:00

from django.db import migrations, models
import uuid
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_alter_taskdeadlinereminder_reminder_type'),
    ]

    operations = [
        # 添加 LockTask 字段
        migrations.AddField(
            model_name='locktask',
            name='allow_temporary_unlock',
            field=models.BooleanField(default=False, help_text='是否允许临时开锁'),
        ),
        migrations.AddField(
            model_name='locktask',
            name='temporary_unlock_limit_type',
            field=models.CharField(
                blank=True,
                choices=[('daily_count', '每日次数'), ('cooldown', '冷却间隔')],
                help_text='临时开锁限制类型',
                max_length=20,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='locktask',
            name='temporary_unlock_limit_value',
            field=models.IntegerField(
                blank=True,
                help_text='限制值（每日次数：x次，或冷却间隔：x小时）',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='locktask',
            name='temporary_unlock_max_duration',
            field=models.IntegerField(default=30, help_text='单次临时开锁最大时长（分钟）'),
        ),
        migrations.AddField(
            model_name='locktask',
            name='temporary_unlock_require_approval',
            field=models.BooleanField(default=False, help_text='是否需要钥匙所有者同意'),
        ),
        migrations.AddField(
            model_name='locktask',
            name='temporary_unlock_require_photo',
            field=models.BooleanField(default=False, help_text='是否需要拍照证明'),
        ),

        # 创建 TemporaryUnlockRecord 模型
        migrations.CreateModel(
            name='TemporaryUnlockRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(
                    choices=[
                        ('pending', '等待批准'),
                        ('approved', '已批准'),
                        ('rejected', '已拒绝'),
                        ('active', '进行中'),
                        ('completed', '已完成'),
                        ('timeout', '超时结束'),
                        ('cancelled', '已取消'),
                    ],
                    default='active',
                    help_text='临时开锁状态',
                    max_length=20
                )),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='请求时间')),
                ('started_at', models.DateTimeField(blank=True, help_text='实际开始时间（批准后开始）', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='结束时间', null=True)),
                ('max_end_time', models.DateTimeField(blank=True, help_text='最大结束时间（用于超时检测）', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='批准时间', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='拒绝原因', max_length=500)),
                ('verification_photo', models.ImageField(
                    blank=True,
                    help_text='验证照片',
                    null=True,
                    upload_to='temporary_unlocks/photos'
                )),
                ('photo_taken_at', models.DateTimeField(blank=True, help_text='拍照时间', null=True)),
                ('task_frozen_end_time', models.DateTimeField(blank=True, help_text='任务冻结时的原始结束时间', null=True)),
                ('penalty_applied', models.BooleanField(default=False, help_text='是否已应用惩罚')),
                ('penalty_minutes', models.IntegerField(default=30, help_text='惩罚时长（分钟）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_holder', models.ForeignKey(
                    blank=True,
                    help_text='批准请求的钥匙持有者',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='approved_unlocks',
                    to=settings.AUTH_USER_MODEL
                )),
                ('task', models.ForeignKey(
                    help_text='关联的锁任务',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='temporary_unlocks',
                    to='tasks.locktask'
                )),
                ('user', models.ForeignKey(
                    help_text='请求临时开锁的用户',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='temporary_unlocks',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': '临时开锁记录',
                'verbose_name_plural': '临时开锁记录',
                'db_table': 'temporary_unlock_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
