# Generated by Django 5.2.11 on 2026-02-23 08:41

import django.db.models.deletion
import utils.file_upload
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_add_temporary_unlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locktask',
            name='daily_task_duration',
            field=models.IntegerField(blank=True, help_text='日常任务持续天数', null=True),
        ),
        migrations.AddField(
            model_name='locktask',
            name='daily_task_publish_time',
            field=models.TimeField(blank=True, help_text='日常任务每日发布时间', null=True),
        ),
        migrations.AddField(
            model_name='locktask',
            name='daily_task_total_cost',
            field=models.IntegerField(blank=True, help_text='日常任务总预扣积分', null=True),
        ),
        migrations.AddField(
            model_name='locktask',
            name='is_daily_task',
            field=models.BooleanField(default=False, help_text='是否为日常任务'),
        ),
        migrations.AlterField(
            model_name='tasktimelineevent',
            name='event_type',
            field=models.CharField(choices=[('task_created', '任务创建'), ('task_started', '任务开始'), ('time_wheel_increase', '时间转盘增加时间'), ('time_wheel_decrease', '时间转盘减少时间'), ('overtime_added', '他人加时'), ('voting_started', '投票期开始'), ('voting_ended', '投票期结束'), ('vote_passed', '投票通过'), ('vote_failed', '投票失败'), ('task_voted', '任务投票'), ('task_completed', '任务完成'), ('task_stopped', '任务停止'), ('task_failed', '任务失败'), ('deadline_extended', '截止时间延长'), ('manual_adjustment', '手动调整'), ('hourly_reward', '小时奖励'), ('task_keys_destroyed', '任务钥匙销毁'), ('user_pinned', '用户被置顶'), ('user_unpinned', '用户置顶结束'), ('pinning_queue_updated', '置顶队列更新'), ('task_frozen', '任务冻结'), ('task_unfrozen', '任务解冻'), ('radar_detection', '探测雷达检测'), ('system_freeze', '系统冻结'), ('verification_code_updated', '验证码更新'), ('item_effect_applied', '道具效果应用'), ('exclusive_task_created', '专属任务创建'), ('board_task_taken', '任务板接取'), ('shield_activated', '防护罩开启'), ('shield_deactivated', '防护罩关闭'), ('temporary_unlock_requested', '临时开锁请求'), ('temporary_unlock_approved', '临时开锁批准'), ('temporary_unlock_rejected', '临时开锁拒绝'), ('temporary_unlock_started', '临时开锁开始'), ('temporary_unlock_ended', '临时开锁结束'), ('temporary_unlock_cancelled', '临时开锁取消'), ('temporary_unlock_timeout', '临时开锁超时')], max_length=30),
        ),
        migrations.AlterField(
            model_name='temporaryunlockrecord',
            name='verification_photo',
            field=models.ImageField(blank=True, help_text='验证照片', null=True, upload_to=utils.file_upload.secure_temporary_unlock_photo_upload_to),
        ),
        migrations.CreateModel(
            name='DailyTaskConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_days', models.IntegerField(help_text='总持续天数')),
                ('publish_time', models.TimeField(help_text='每日发布时间')),
                ('total_cost', models.IntegerField(help_text='总预扣积分')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', help_text='日常任务状态', max_length=20)),
                ('remaining_days', models.IntegerField(default=0, help_text='剩余天数')),
                ('published_count', models.IntegerField(default=0, help_text='已发布天数')),
                ('next_publish_at', models.DateTimeField(blank=True, help_text='下次发布时间', null=True)),
                ('refunded_coins', models.IntegerField(default=0, help_text='已退还积分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='取消时间', null=True)),
                ('parent_task', models.ForeignKey(help_text='父任务（创建日常任务的原始任务）', on_delete=django.db.models.deletion.CASCADE, related_name='daily_task_configs', to='tasks.locktask')),
                ('user', models.ForeignKey(help_text='创建者', on_delete=django.db.models.deletion.CASCADE, related_name='daily_task_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日常任务配置',
                'verbose_name_plural': '日常任务配置',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='tasks_daily_user_id_7a6fc1_idx'), models.Index(fields=['status', 'next_publish_at'], name='tasks_daily_status_223dd4_idx'), models.Index(fields=['created_at'], name='tasks_daily_created_474443_idx')],
            },
        ),
    ]
