# Generated by Django 5.2.11 on 2026-04-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantom_city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamezone',
            name='name',
            field=models.CharField(choices=[('ruins', '污染废墟'), ('ruins_deep', '废墟深处'), ('salon', '纯净沙龙'), ('black_market', '黑市街道'), ('checkpoint', '铁血防线'), ('abandoned_camp', '废弃营地'), ('interrogation_room', '审讯室'), ('control_room', '控制室')], max_length=20, unique=True),
        ),
    ]
