# Generated by Django 5.2.11 on 2026-04-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantom_city', '0002_alter_gamezone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamezone',
            name='name',
            field=models.CharField(choices=[('ruins', '污染废墟'), ('ruins_deep', '废墟深处'), ('ruins_outer', '废墟外围'), ('salon', '纯净沙龙'), ('black_market', '黑市街道'), ('armory', '军火库'), ('checkpoint', '铁血防线'), ('abandoned_camp', '废弃营地'), ('sewer', '污水管道'), ('interrogation_room', '审讯室'), ('control_room', '控制室')], max_length=20, unique=True),
        ),
    ]
