# Generated by Django 5.2.11 on 2026-04-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantom_city', '0003_alter_gamezone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='graymarkettransaction',
            name='zone_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='graymarkettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('bribe', '贿赂'), ('extortion', '勒索'), ('trade', '交易'), ('armory_toll', '军火库通行费')], max_length=15),
        ),
    ]
