# Generated by Django 5.2.7 on 2025-10-11 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '评论点赞',
                'verbose_name_plural': '评论点赞',
                'db_table': 'comment_likes',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('normal', '普通动态'), ('checkin', '打卡任务')], default='normal', help_text='动态类型', max_length=10)),
                ('content', models.TextField(help_text='动态内容', max_length=2000)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='纬度', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='经度', max_digits=10, null=True)),
                ('location_name', models.CharField(blank=True, help_text='位置名称', max_length=200)),
                ('verification_string', models.CharField(blank=True, help_text='验证字符串（用于打卡任务）', max_length=50)),
                ('is_verified', models.BooleanField(default=False, help_text='是否已验证')),
                ('likes_count', models.IntegerField(default=0, help_text='点赞数')),
                ('comments_count', models.IntegerField(default=0, help_text='评论数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='图片文件', upload_to='posts/images/')),
                ('order', models.IntegerField(default=0, help_text='图片顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '动态图片',
                'verbose_name_plural': '动态图片',
                'db_table': 'post_images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '动态点赞',
                'verbose_name_plural': '动态点赞',
                'db_table': 'post_likes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='评论内容', max_length=500)),
                ('likes_count', models.IntegerField(default=0, help_text='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='父评论（用于回复）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
    ]
