# Generated by Django 5.2.7 on 2025-10-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='图片文件', upload_to='comments/images/')),
                ('order', models.IntegerField(default=0, help_text='图片顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(help_text='所属评论', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.comment')),
            ],
            options={
                'verbose_name': '评论图片',
                'verbose_name_plural': '评论图片',
                'db_table': 'comment_images',
                'ordering': ['order'],
            },
        ),
    ]
