# Generated by Django 5.2.7 on 2025-12-14 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_commentimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.IntegerField(default=0, help_text='评论层级深度 - 0为第一层，1为第二层'),
        ),
        migrations.AddField(
            model_name='comment',
            name='path',
            field=models.CharField(default='', help_text='物化路径 - 格式: root_id 或 root_id.child_id', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies_count',
            field=models.IntegerField(default=0, help_text='回复数（仅第一层使用）'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to_user',
            field=models.ForeignKey(blank=True, help_text="被回复的用户（用于第二层显示 '@用户名'）", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='root_reply_id',
            field=models.UUIDField(blank=True, help_text='根回复ID - 第一层评论为null，第二层评论指向第一层', null=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'root_reply_id'], name='comments_post_id_634653_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['path'], name='comments_path_7d0049_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['depth'], name='comments_depth_2b9bd5_idx'),
        ),
    ]
