# Generated by Django 5.2.7 on 2025-12-14 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_depth_comment_path_comment_replies_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, help_text='实际被回复的评论（保存真实的回复关系）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_replies', to='posts.comment'),
        ),
    ]
