# Generated by Django 5.2.7 on 2025-12-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_add_reply_to_comment_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_to_comment',
        ),
    ]
