# Generated by Django 5.2.7 on 2025-12-20 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_reply_to_comment_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('pass', '通过'), ('reject', '拒绝')], help_text='投票类型', max_length=10)),
                ('coins_spent', models.IntegerField(default=5, help_text='投票花费的积分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(help_text='投票的打卡动态', on_delete=django.db.models.deletion.CASCADE, related_name='checkin_votes', to='posts.post')),
                ('voter', models.ForeignKey(help_text='投票用户', on_delete=django.db.models.deletion.CASCADE, related_name='checkin_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '打卡投票',
                'verbose_name_plural': '打卡投票',
                'db_table': 'checkin_votes',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'voter')},
            },
        ),
        migrations.CreateModel(
            name='CheckinVotingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voting_deadline', models.DateTimeField(help_text='投票截止时间（次日凌晨4点）')),
                ('total_coins_collected', models.IntegerField(default=0, help_text='收集的总积分')),
                ('is_processed', models.BooleanField(default=False, help_text='是否已处理投票结果')),
                ('result', models.CharField(choices=[('pending', '等待投票'), ('passed', '投票通过'), ('rejected', '投票拒绝')], default='pending', help_text='投票结果', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='处理时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(help_text='投票的打卡动态', on_delete=django.db.models.deletion.CASCADE, related_name='voting_session', to='posts.post')),
            ],
            options={
                'verbose_name': '打卡投票会话',
                'verbose_name_plural': '打卡投票会话',
                'db_table': 'checkin_voting_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['voting_deadline', 'is_processed'], name='checkin_vot_voting__0ddfcc_idx'), models.Index(fields=['result'], name='checkin_vot_result_36c211_idx')],
            },
        ),
    ]
