# Generated by Django 5.2.7 on 2025-12-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_add_checkin_voting_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimage',
            name='image',
            field=models.ImageField(help_text='评论图片文件', upload_to='utils.file_upload.secure_comment_image_upload_to'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(help_text='动态图片文件', upload_to='utils.file_upload.secure_post_image_upload_to'),
        ),
    ]
