# Generated by Django 5.2.7 on 2025-12-21 10:51

import utils.file_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_commentimage_image_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimage',
            name='image',
            field=models.ImageField(help_text='评论图片文件', upload_to=utils.file_upload.secure_comment_image_upload_to),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(help_text='动态图片文件', upload_to=utils.file_upload.secure_post_image_upload_to),
        ),
    ]
