# Generated by Django 5.2.11 on 2026-02-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_commentimage_image_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='评论内容（HTML格式，实际显示文本限制500字符）', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='动态内容（HTML格式，实际显示文本限制1500字符）', max_length=5000),
        ),
    ]
