# Generated by Django 5.2.7 on 2025-10-11 08:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('level', models.IntegerField(default=1, help_text='用户等级 1-4', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('activity_score', models.IntegerField(default=0, help_text='活跃度积分')),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, help_text='最后活跃时间')),
                ('location_precision', models.IntegerField(default=100, help_text='地理位置精确度（米）')),
                ('coins', models.IntegerField(default=0, help_text='金币数量')),
                ('avatar', models.ImageField(blank=True, help_text='头像', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='个人简介', max_length=500)),
                ('total_posts', models.IntegerField(default=0, help_text='发布动态总数')),
                ('total_likes_received', models.IntegerField(default=0, help_text='收到点赞总数')),
                ('total_tasks_completed', models.IntegerField(default=0, help_text='完成任务总数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserLevelUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.IntegerField(help_text='原等级')),
                ('to_level', models.IntegerField(help_text='新等级')),
                ('reason', models.CharField(choices=[('activity', '活跃度达标'), ('manual', '手动晋升'), ('downgrade', '降级')], help_text='晋升原因', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_by', models.ForeignKey(blank=True, help_text='执行晋升的4级用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='被晋升的用户', on_delete=django.db.models.deletion.CASCADE, related_name='level_upgrades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '等级晋升记录',
                'verbose_name_plural': '等级晋升记录',
                'db_table': 'user_level_upgrades',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已接受'), ('blocked', '已屏蔽')], default='pending', help_text='好友关系状态', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(help_text='发起好友请求的用户', on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(help_text='接收好友请求的用户', on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '好友关系',
                'verbose_name_plural': '好友关系',
                'db_table': 'friendships',
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
