# Generated by Django 5.2.7 on 2025-10-13 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLoginReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='奖励日期')),
                ('user_level', models.IntegerField(help_text='用户等级')),
                ('reward_amount', models.IntegerField(help_text='奖励积分数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='获得奖励的用户', on_delete=django.db.models.deletion.CASCADE, related_name='daily_login_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '每日登录奖励',
                'verbose_name_plural': '每日登录奖励',
                'db_table': 'daily_login_rewards',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
