# Generated by Django 5.2.7 on 2025-10-13 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dailyloginreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('post_liked', '动态被点赞'), ('post_commented', '动态被评论'), ('comment_liked', '评论被点赞'), ('comment_replied', '评论被回复'), ('task_overtime_added', '任务被他人加时'), ('task_board_taken', '任务板任务被接取'), ('task_board_submitted', '任务板任务被提交'), ('task_board_approved', '任务板任务被审核通过'), ('task_board_rejected', '任务板任务被拒绝'), ('coins_earned_hourly', '小时奖励积分'), ('coins_earned_daily_login', '每日登录奖励积分'), ('coins_earned_task_reward', '任务奖励积分'), ('coins_spent_task_creation', '创建任务消耗积分'), ('treasure_found', '掩埋物品被发现'), ('photo_viewed', '照片被查看'), ('drift_bottle_found', '漂流瓶被发现'), ('item_received', '收到物品'), ('friend_request', '好友请求'), ('friend_accepted', '好友请求被接受'), ('level_upgraded', '等级提升'), ('system_announcement', '系统公告')], help_text='通知类型', max_length=30)),
                ('title', models.CharField(help_text='通知标题', max_length=200)),
                ('message', models.TextField(help_text='通知内容', max_length=500)),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', help_text='通知优先级', max_length=10)),
                ('related_object_type', models.CharField(blank=True, help_text='关联对象类型 (如: post, task, comment 等)', max_length=50, null=True)),
                ('related_object_id', models.CharField(blank=True, help_text='关联对象ID', max_length=50, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='额外的通知数据')),
                ('is_read', models.BooleanField(default=False, help_text='是否已读')),
                ('read_at', models.DateTimeField(blank=True, help_text='读取时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, help_text='触发通知的用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='接收通知的用户', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_498289_idx')],
            },
        ),
    ]
