# Generated by Django 5.2.7 on 2025-12-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_bound_at',
            field=models.DateTimeField(blank=True, help_text='Telegram 绑定时间', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram 聊天ID', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=True, help_text='是否启用 Telegram 通知'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram 用户ID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram 用户名', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_liked', '动态被点赞'), ('post_commented', '动态被评论'), ('comment_liked', '评论被点赞'), ('comment_replied', '评论被回复'), ('task_overtime_added', '任务被他人加时'), ('task_board_taken', '任务板任务被接取'), ('task_board_submitted', '任务板任务被提交'), ('task_board_approved', '任务板任务被审核通过'), ('task_board_rejected', '任务板任务被拒绝'), ('coins_earned_hourly', '小时奖励积分'), ('coins_earned_hourly_batch', '批量小时奖励积分'), ('coins_earned_daily_login', '每日登录奖励积分'), ('coins_earned_task_reward', '任务奖励积分'), ('coins_spent_task_creation', '创建任务消耗积分'), ('treasure_found', '掩埋物品被发现'), ('photo_viewed', '照片被查看'), ('drift_bottle_found', '漂流瓶被发现'), ('item_received', '收到物品'), ('friend_request', '好友请求'), ('friend_accepted', '好友请求被接受'), ('level_upgraded', '等级提升'), ('system_announcement', '系统公告')], help_text='通知类型', max_length=30),
        ),
    ]
