# Generated by Django 5.2.7 on 2025-12-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_telegram_binding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_binding_token',
            field=models.CharField(blank=True, help_text='临时绑定令牌，用于自动绑定流程', max_length=100, null=True),
        ),
    ]
