# Generated by Django 5.2.7 on 2025-12-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_daily_checkin_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_telegram_account',
            field=models.BooleanField(default=False, help_text='是否在个人资料中展示 Telegram 账号'),
        ),
    ]
