# Generated by Django 5.2.7 on 2025-12-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_voting_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='用户头像', null=True, upload_to='utils.file_upload.secure_avatar_upload_to'),
        ),
    ]
