# Generated by Django 5.2.7 on 2025-12-24 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_auto_freeze_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_decay_processed',
            field=models.DateTimeField(blank=True, help_text='最后一次处理衰减的时间', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_liked', '动态被点赞'), ('post_commented', '动态被评论'), ('comment_liked', '评论被点赞'), ('comment_replied', '评论被回复'), ('task_overtime_added', '任务被他人加时'), ('task_board_taken', '任务板任务被接取'), ('task_board_submitted', '任务板任务被提交'), ('task_board_approved', '任务板任务被审核通过'), ('task_board_rejected', '任务板任务被拒绝'), ('checkin_vote_cast', '打卡投票'), ('checkin_vote_passed', '打卡投票通过'), ('checkin_vote_rejected', '打卡投票拒绝'), ('checkin_vote_reward', '打卡投票奖励'), ('task_frozen_by_vote', '投票冻结任务'), ('task_frozen_auto_strict', '严格模式自动冻结任务'), ('task_failed_by_vote', '投票失败任务'), ('coins_earned_hourly', '小时奖励积分'), ('coins_earned_hourly_batch', '批量小时奖励积分'), ('coins_earned_daily_login', '每日登录奖励积分'), ('coins_earned_daily_checkin', '每日首次打卡奖励积分'), ('coins_earned_daily_board_post', '每日首次发布任务板奖励积分'), ('coins_earned_task_reward', '任务奖励积分'), ('coins_spent_task_creation', '创建任务消耗积分'), ('treasure_found', '掩埋物品被发现'), ('photo_viewed', '照片被查看'), ('note_viewed', '纸条被查看'), ('drift_bottle_found', '漂流瓶被发现'), ('item_received', '收到物品'), ('friend_request', '好友请求'), ('friend_accepted', '好友请求被接受'), ('level_upgraded', '等级提升'), ('system_announcement', '系统公告')], help_text='通知类型', max_length=30),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('activity_gain', '活跃度获得'), ('time_decay', '时间衰减')], help_text='活动类型', max_length=50)),
                ('points_change', models.IntegerField(help_text='积分变化（正数为增加，负数为减少）')),
                ('new_total', models.IntegerField(help_text='变化后的总积分')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='额外的元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='相关用户', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '活跃度日志',
                'verbose_name_plural': '活跃度日志',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx'), models.Index(fields=['action_type', '-created_at'], name='activity_lo_action__5e24c2_idx')],
            },
        ),
    ]
