# Generated by Django 5.2.7 on 2025-12-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_liked', '动态被点赞'), ('post_commented', '动态被评论'), ('comment_liked', '评论被点赞'), ('comment_replied', '评论被回复'), ('task_overtime_added', '任务被他人加时'), ('task_board_taken', '任务板任务被接取'), ('task_board_submitted', '任务板任务被提交'), ('task_board_approved', '任务板任务被审核通过'), ('task_board_rejected', '任务板任务被拒绝'), ('task_board_assigned_exclusive', '专属任务指派'), ('task_deadline_reminder_8h', '任务截止前8小时提醒'), ('checkin_vote_cast', '打卡投票'), ('checkin_vote_passed', '打卡投票通过'), ('checkin_vote_rejected', '打卡投票拒绝'), ('checkin_vote_reward', '打卡投票奖励'), ('checkin_vote_passed_voter', '投票成功通知（投票者）'), ('task_frozen_by_vote', '投票冻结任务'), ('task_frozen_auto_strict', '严格模式自动冻结任务'), ('task_failed_by_vote', '投票失败任务'), ('coins_earned_hourly', '小时奖励积分'), ('coins_earned_hourly_batch', '批量小时奖励积分'), ('coins_earned_daily_login', '每日登录奖励积分'), ('coins_earned_daily_checkin', '每日首次打卡奖励积分'), ('coins_earned_daily_board_post', '每日首次发布任务板奖励积分'), ('coins_earned_task_reward', '任务奖励积分'), ('coins_spent_task_creation', '创建任务消耗积分'), ('treasure_found', '掩埋物品被发现'), ('photo_viewed', '照片被查看'), ('note_viewed', '纸条被查看'), ('drift_bottle_found', '漂流瓶被发现'), ('item_received', '收到物品'), ('friend_request', '好友请求'), ('friend_accepted', '好友请求被接受'), ('level_upgraded', '等级提升'), ('system_announcement', '系统公告'), ('system_event_occurred', '系统事件发生')], help_text='通知类型', max_length=30),
        ),
    ]
