# Generated by Django 5.2.7 on 2026-01-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='待验证的邮箱地址', max_length=254)),
                ('verification_code', models.CharField(help_text='6位数字验证码', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('expires_at', models.DateTimeField(help_text='过期时间')),
                ('is_used', models.BooleanField(default=False, help_text='是否已使用')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='请求IP地址', null=True)),
            ],
            options={
                'verbose_name': '邮箱验证',
                'verbose_name_plural': '邮箱验证',
                'db_table': 'email_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='email_verif_email_f2df17_idx'), models.Index(fields=['verification_code'], name='email_verif_verific_c3df34_idx'), models.Index(fields=['expires_at'], name='email_verif_expires_fdd67c_idx')],
            },
        ),
    ]
