# Generated by Django 5.2.7 on 2026-01-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='待重置密码的邮箱地址', max_length=254)),
                ('reset_code', models.CharField(help_text='6位数字重置码', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('expires_at', models.DateTimeField(help_text='过期时间')),
                ('is_used', models.BooleanField(default=False, help_text='是否已使用')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='请求IP地址', null=True)),
            ],
            options={
                'verbose_name': '密码重置',
                'verbose_name_plural': '密码重置',
                'db_table': 'password_resets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='password_re_email_226075_idx'), models.Index(fields=['reset_code'], name='password_re_reset_c_5a5945_idx'), models.Index(fields=['expires_at'], name='password_re_expires_d36310_idx')],
            },
        ),
    ]
