# Generated by Django 5.2.11 on 2026-02-21 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_add_password_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('hourly_reward', '小时奖励'), ('daily_login', '每日登录奖励'), ('task_complete', '任务完成奖励'), ('board_task_reward', '任务板奖励'), ('event_reward', '活动奖励'), ('admin_grant', '管理员发放'), ('other_income', '其他收入'), ('task_creation', '创建任务消耗'), ('store_purchase', '商店购买'), ('event_cost', '活动消耗'), ('admin_deduct', '管理员扣除'), ('other_expense', '其他支出')], max_length=30)),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '积分日志',
                'verbose_name_plural': '积分日志',
                'db_table': 'coins_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='coins_logs_user_id_5b35b1_idx'), models.Index(fields=['change_type', '-created_at'], name='coins_logs_change__17ba23_idx')],
            },
        ),
    ]
