# Generated by Django 5.2.11 on 2026-02-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_conversation_and_private_message'),
        ('users', '0018_coinslog'),
    ]

    operations = [
    ]
