# Generated by Django 5.2.7 on 2026-02-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_merge_20260221_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='message_type',
            field=models.CharField(
                choices=[('text', '文本'), ('image', '图片'), ('voice', '语音')],
                default='text',
                help_text='消息类型',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='file_url',
            field=models.URLField(
                blank=True,
                help_text='图片/语音文件URL',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='file_duration',
            field=models.IntegerField(
                blank=True,
                help_text='语音时长（秒）',
                null=True
            ),
        ),
    ]
