# Generated by Django 5.2.11 on 2026-02-21 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_add_message_type_to_private_message'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_updated_c163ba_idx',
            old_name='conversations_updated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='privatemessage',
            new_name='private_mes_convers_bde32d_idx',
            old_name='private_messages_conv_created_idx',
        ),
        migrations.RenameIndex(
            model_name='privatemessage',
            new_name='private_mes_convers_299507_idx',
            old_name='private_messages_conv_read_idx',
        ),
        migrations.RenameIndex(
            model_name='privatemessage',
            new_name='private_mes_sender__f075d5_idx',
            old_name='private_messages_sender_created_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='task_deadline_reminder_minutes',
            field=models.IntegerField(default=30, help_text='任务截止前提醒时间（分钟），范围 5-120', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_min_priority',
            field=models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='urgent', help_text='Telegram 通知最低优先级', max_length=10),
        ),
        migrations.AlterField(
            model_name='coinslog',
            name='change_type',
            field=models.CharField(choices=[('hourly_reward', '小时奖励'), ('daily_login', '每日登录奖励'), ('daily_checkin', '每日首次打卡奖励'), ('daily_board_post', '每日首次发布任务板奖励'), ('task_complete', '任务完成奖励'), ('task_completion_bonus', '任务完成额外奖励'), ('board_task_reward', '任务板奖励'), ('treasure_discovered', '宝物被发现奖励'), ('game_refund', '游戏退款'), ('treasury_withdrawal', '小金库提取'), ('event_reward', '活动奖励'), ('admin_grant', '管理员发放'), ('other_income', '其他收入'), ('task_creation', '创建任务消耗'), ('checkin_vote', '打卡投票消耗'), ('game_participation', '游戏参与消耗'), ('exploration', '探索消耗'), ('time_wheel_adjustment', '时间转盘调整费用'), ('store_purchase', '商店购买'), ('event_cost', '活动消耗'), ('admin_deduct', '管理员扣除'), ('other_expense', '其他支出')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_liked', '动态被点赞'), ('post_commented', '动态被评论'), ('comment_liked', '评论被点赞'), ('comment_replied', '评论被回复'), ('task_overtime_added', '任务被他人加时'), ('task_board_taken', '任务板任务被接取'), ('task_board_submitted', '任务板任务被提交'), ('task_board_approved', '任务板任务被审核通过'), ('task_board_rejected', '任务板任务被拒绝'), ('task_board_assigned_exclusive', '专属任务指派'), ('task_deadline_reminder_8h', '任务截止前8小时提醒'), ('task_deadline_reminder_custom', '任务截止前自定义时间提醒'), ('checkin_vote_cast', '打卡投票'), ('checkin_vote_passed', '打卡投票通过'), ('checkin_vote_rejected', '打卡投票拒绝'), ('checkin_vote_reward', '打卡投票奖励'), ('checkin_vote_passed_voter', '投票成功通知（投票者）'), ('task_frozen_by_vote', '投票冻结任务'), ('task_frozen_auto_strict', '严格模式自动冻结任务'), ('task_failed_by_vote', '投票失败任务'), ('coins_earned_hourly', '小时奖励积分'), ('coins_earned_hourly_batch', '批量小时奖励积分'), ('coins_earned_daily_login', '每日登录奖励积分'), ('coins_earned_daily_checkin', '每日首次打卡奖励积分'), ('coins_earned_daily_board_post', '每日首次发布任务板奖励积分'), ('coins_earned_task_reward', '任务奖励积分'), ('coins_spent_task_creation', '创建任务消耗积分'), ('treasure_found', '掩埋物品被发现'), ('photo_viewed', '照片被查看'), ('note_viewed', '纸条被查看'), ('drift_bottle_found', '漂流瓶被发现'), ('item_received', '收到物品'), ('friend_request', '好友请求'), ('friend_accepted', '好友请求被接受'), ('private_message', '收到私信'), ('level_upgraded', '等级提升'), ('system_announcement', '系统公告'), ('system_event_occurred', '系统事件发生')], help_text='通知类型', max_length=30),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='content',
            field=models.TextField(help_text='消息内容（文本内容或图片描述）', max_length=2000),
        ),
    ]
