# Generated by Django 5.2.11 on 2026-02-21 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_conversations_updated_at_idx_conversatio_updated_c163ba_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyloginreward',
            options={'verbose_name': '每日登录奖励（已废弃）', 'verbose_name_plural': '每日登录奖励（已废弃）'},
        ),
        migrations.CreateModel(
            name='UserCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_date', models.DateField(help_text='签到日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coins_earned', models.IntegerField(default=0, help_text='获得的积分数量')),
                ('consecutive_days', models.IntegerField(default=1, help_text='连续签到天数')),
                ('user', models.ForeignKey(help_text='签到用户', on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户签到记录',
                'verbose_name_plural': '用户签到记录',
                'db_table': 'user_checkins',
                'ordering': ['-check_in_date'],
                'unique_together': {('user', 'check_in_date')},
            },
        ),
    ]
